PalletLocation.create(pallet_id: 1, location_id: 2)
PalletLocation.create(pallet_id: 2, location_id: 3)
PalletLocation.create(pallet_id: 3, location_id: 4)
PalletLocation.create(pallet_id: 5, location_id: 5)
PalletLocation.create(pallet_id: 6, location_id: 68)
PalletLocation.create(pallet_id: 7, location_id: 69)
PalletLocation.create(pallet_id: 8, location_id: 70)
PalletLocation.create(pallet_id: 9, location_id: 71)
PalletLocation.create(pallet_id: 11, location_id: 134)
PalletLocation.create(pallet_id: 12, location_id: 135)
PalletLocation.create(pallet_id: 13, location_id: 136)
PalletLocation.create(pallet_id: 4, location_id: 137)
PalletLocation.create(pallet_id: 15, location_id: 138)
PalletLocation.create(pallet_id: 16, location_id: 200)
PalletLocation.create(pallet_id: 17, location_id: 201)
PalletLocation.create(pallet_id: 10, location_id: 203)
PalletLocation.create(pallet_id: 18, location_id: 202)
PalletLocation.create(pallet_id: 20, location_id: 266)
PalletLocation.create(pallet_id: 21, location_id: 267)
PalletLocation.create(pallet_id: 22, location_id: 268)
PalletLocation.create(pallet_id: 23, location_id: 269)
PalletLocation.create(pallet_id: 24, location_id: 270)
PalletLocation.create(pallet_id: 25, location_id: 332)
PalletLocation.create(pallet_id: 26, location_id: 333)
PalletLocation.create(pallet_id: 27, location_id: 334)
PalletLocation.create(pallet_id: 28, location_id: 335)
PalletLocation.create(pallet_id: 29, location_id: 398)
PalletLocation.create(pallet_id: 30, location_id: 399)
PalletLocation.create(pallet_id: 31, location_id: 401)
PalletLocation.create(pallet_id: 32, location_id: 464)
PalletLocation.create(pallet_id: 33, location_id: 466)
PalletLocation.create(pallet_id: 34, location_id: 465)
PalletLocation.create(pallet_id: 35, location_id: 525)
PalletLocation.create(pallet_id: 36, location_id: 527)
PalletLocation.create(pallet_id: 37, location_id: 8)
PalletLocation.create(pallet_id: 38, location_id: 9)
PalletLocation.create(pallet_id: 39, location_id: 11)
PalletLocation.create(pallet_id: 40, location_id: 400)
PalletLocation.create(pallet_id: 41, location_id: 526)
PalletLocation.create(pallet_id: 42, location_id: 10)
PalletLocation.create(pallet_id: 43, location_id: 14)
PalletLocation.create(pallet_id: 44, location_id: 15)
PalletLocation.create(pallet_id: 14, location_id: 16)
PalletLocation.create(pallet_id: 19, location_id: 17)
PalletLocation.create(pallet_id: 45, location_id: 467)
PalletLocation.create(pallet_id: 46, location_id: 524)
PalletLocation.create(pallet_id: 48, location_id: 18)
PalletLocation.create(pallet_id: 49, location_id: 20)
PalletLocation.create(pallet_id: 50, location_id: 21)
PalletLocation.create(pallet_id: 47, location_id: 23)
PalletLocation.create(pallet_id: 51, location_id: 22)
PalletLocation.create(pallet_id: 52, location_id: 26)
PalletLocation.create(pallet_id: 55, location_id: 29)
PalletLocation.create(pallet_id: 56, location_id: 30)
PalletLocation.create(pallet_id: 57, location_id: 32)
PalletLocation.create(pallet_id: 58, location_id: 34)
PalletLocation.create(pallet_id: 59, location_id: 33)
PalletLocation.create(pallet_id: 60, location_id: 35)
PalletLocation.create(pallet_id: 61, location_id: 38)
PalletLocation.create(pallet_id: 62, location_id: 39)
PalletLocation.create(pallet_id: 63, location_id: 40)
PalletLocation.create(pallet_id: 64, location_id: 41)
PalletLocation.create(pallet_id: 65, location_id: 42)
PalletLocation.create(pallet_id: 66, location_id: 44)
PalletLocation.create(pallet_id: 67, location_id: 45)
PalletLocation.create(pallet_id: 68, location_id: 46)
PalletLocation.create(pallet_id: 69, location_id: 47)
PalletLocation.create(pallet_id: 70, location_id: 50)
PalletLocation.create(pallet_id: 71, location_id: 51)
PalletLocation.create(pallet_id: 72, location_id: 52)
PalletLocation.create(pallet_id: 73, location_id: 53)
PalletLocation.create(pallet_id: 74, location_id: 56)
PalletLocation.create(pallet_id: 75, location_id: 57)
PalletLocation.create(pallet_id: 76, location_id: 58)
PalletLocation.create(pallet_id: 77, location_id: 59)
PalletLocation.create(pallet_id: 78, location_id: 62)
PalletLocation.create(pallet_id: 79, location_id: 63)
PalletLocation.create(pallet_id: 80, location_id: 64)
PalletLocation.create(pallet_id: 81, location_id: 65)
PalletLocation.create(pallet_id: 82, location_id: 74)
PalletLocation.create(pallet_id: 83, location_id: 75)
PalletLocation.create(pallet_id: 84, location_id: 76)
PalletLocation.create(pallet_id: 85, location_id: 77)
PalletLocation.create(pallet_id: 86, location_id: 80)
PalletLocation.create(pallet_id: 87, location_id: 81)
PalletLocation.create(pallet_id: 88, location_id: 82)
PalletLocation.create(pallet_id: 89, location_id: 83)
PalletLocation.create(pallet_id: 90, location_id: 86)
PalletLocation.create(pallet_id: 91, location_id: 87)
PalletLocation.create(pallet_id: 92, location_id: 88)
PalletLocation.create(pallet_id: 93, location_id: 89)
PalletLocation.create(pallet_id: 94, location_id: 92)
PalletLocation.create(pallet_id: 95, location_id: 93)
PalletLocation.create(pallet_id: 96, location_id: 94)
PalletLocation.create(pallet_id: 97, location_id: 95)
PalletLocation.create(pallet_id: 98, location_id: 98)
PalletLocation.create(pallet_id: 99, location_id: 99)
PalletLocation.create(pallet_id: 100, location_id: 100)
PalletLocation.create(pallet_id: 101, location_id: 101)
PalletLocation.create(pallet_id: 102, location_id: 104)
PalletLocation.create(pallet_id: 103, location_id: 105)
PalletLocation.create(pallet_id: 105, location_id: 107)
PalletLocation.create(pallet_id: 106, location_id: 110)
PalletLocation.create(pallet_id: 107, location_id: 111)
PalletLocation.create(pallet_id: 108, location_id: 112)
PalletLocation.create(pallet_id: 110, location_id: 116)
PalletLocation.create(pallet_id: 111, location_id: 117)
PalletLocation.create(pallet_id: 112, location_id: 118)
PalletLocation.create(pallet_id: 113, location_id: 119)
PalletLocation.create(pallet_id: 114, location_id: 122)
PalletLocation.create(pallet_id: 115, location_id: 123)
PalletLocation.create(pallet_id: 116, location_id: 124)
PalletLocation.create(pallet_id: 117, location_id: 125)
PalletLocation.create(pallet_id: 118, location_id: 128)
PalletLocation.create(pallet_id: 119, location_id: 129)
PalletLocation.create(pallet_id: 120, location_id: 130)
PalletLocation.create(pallet_id: 121, location_id: 131)
PalletLocation.create(pallet_id: 122, location_id: 140)
PalletLocation.create(pallet_id: 123, location_id: 141)
PalletLocation.create(pallet_id: 124, location_id: 142)
PalletLocation.create(pallet_id: 125, location_id: 143)
PalletLocation.create(pallet_id: 126, location_id: 146)
PalletLocation.create(pallet_id: 127, location_id: 147)
PalletLocation.create(pallet_id: 109, location_id: 113)
PalletLocation.create(pallet_id: 128, location_id: 148)
PalletLocation.create(pallet_id: 129, location_id: 149)
PalletLocation.create(pallet_id: 54, location_id: 28)
PalletLocation.create(pallet_id: 53, location_id: 27)
PalletLocation.create(pallet_id: 130, location_id: 152)
PalletLocation.create(pallet_id: 131, location_id: 153)
PalletLocation.create(pallet_id: 132, location_id: 154)
PalletLocation.create(pallet_id: 133, location_id: 155)
PalletLocation.create(pallet_id: 134, location_id: 158)
PalletLocation.create(pallet_id: 137, location_id: 161)
PalletLocation.create(pallet_id: 139, location_id: 165)
PalletLocation.create(pallet_id: 140, location_id: 166)
PalletLocation.create(pallet_id: 141, location_id: 167)
PalletLocation.create(pallet_id: 142, location_id: 170)
PalletLocation.create(pallet_id: 143, location_id: 171)
PalletLocation.create(pallet_id: 144, location_id: 172)
PalletLocation.create(pallet_id: 145, location_id: 173)
PalletLocation.create(pallet_id: 146, location_id: 176)
PalletLocation.create(pallet_id: 147, location_id: 177)
PalletLocation.create(pallet_id: 148, location_id: 178)
PalletLocation.create(pallet_id: 149, location_id: 179)
PalletLocation.create(pallet_id: 150, location_id: 182)
PalletLocation.create(pallet_id: 151, location_id: 183)
PalletLocation.create(pallet_id: 152, location_id: 184)
PalletLocation.create(pallet_id: 153, location_id: 185)
PalletLocation.create(pallet_id: 154, location_id: 188)
PalletLocation.create(pallet_id: 155, location_id: 189)
PalletLocation.create(pallet_id: 156, location_id: 190)
PalletLocation.create(pallet_id: 157, location_id: 191)
PalletLocation.create(pallet_id: 158, location_id: 194)
PalletLocation.create(pallet_id: 159, location_id: 195)
PalletLocation.create(pallet_id: 160, location_id: 196)
PalletLocation.create(pallet_id: 136, location_id: 160)
PalletLocation.create(pallet_id: 104, location_id: 106)
PalletLocation.create(pallet_id: 135, location_id: 159)
PalletLocation.create(pallet_id: 138, location_id: 164)
PalletLocation.create(pallet_id: 161, location_id: 197)
PalletLocation.create(pallet_id: 162, location_id: 206)
PalletLocation.create(pallet_id: 163, location_id: 207)
PalletLocation.create(pallet_id: 164, location_id: 208)
PalletLocation.create(pallet_id: 165, location_id: 209)
PalletLocation.create(pallet_id: 166, location_id: 212)
PalletLocation.create(pallet_id: 167, location_id: 213)
PalletLocation.create(pallet_id: 168, location_id: 214)
PalletLocation.create(pallet_id: 169, location_id: 215)
PalletLocation.create(pallet_id: 170, location_id: 218)
PalletLocation.create(pallet_id: 171, location_id: 219)
PalletLocation.create(pallet_id: 172, location_id: 220)
PalletLocation.create(pallet_id: 173, location_id: 221)
PalletLocation.create(pallet_id: 174, location_id: 224)
PalletLocation.create(pallet_id: 175, location_id: 225)
PalletLocation.create(pallet_id: 176, location_id: 226)
PalletLocation.create(pallet_id: 177, location_id: 227)
PalletLocation.create(pallet_id: 178, location_id: 230)
PalletLocation.create(pallet_id: 179, location_id: 231)
PalletLocation.create(pallet_id: 180, location_id: 232)
PalletLocation.create(pallet_id: 181, location_id: 233)
PalletLocation.create(pallet_id: 182, location_id: 236)
PalletLocation.create(pallet_id: 183, location_id: 237)
PalletLocation.create(pallet_id: 184, location_id: 238)
PalletLocation.create(pallet_id: 186, location_id: 242)
PalletLocation.create(pallet_id: 187, location_id: 243)
PalletLocation.create(pallet_id: 185, location_id: 239)
PalletLocation.create(pallet_id: 189, location_id: 245)
PalletLocation.create(pallet_id: 190, location_id: 248)
PalletLocation.create(pallet_id: 192, location_id: 250)
PalletLocation.create(pallet_id: 194, location_id: 254)
PalletLocation.create(pallet_id: 195, location_id: 255)
PalletLocation.create(pallet_id: 196, location_id: 256)
PalletLocation.create(pallet_id: 197, location_id: 257)
PalletLocation.create(pallet_id: 198, location_id: 260)
PalletLocation.create(pallet_id: 199, location_id: 261)
PalletLocation.create(pallet_id: 200, location_id: 262)
PalletLocation.create(pallet_id: 201, location_id: 263)
PalletLocation.create(pallet_id: 191, location_id: 249)
PalletLocation.create(pallet_id: 202, location_id: 272)
PalletLocation.create(pallet_id: 203, location_id: 273)
PalletLocation.create(pallet_id: 204, location_id: 274)
PalletLocation.create(pallet_id: 205, location_id: 275)
PalletLocation.create(pallet_id: 206, location_id: 279)
PalletLocation.create(pallet_id: 207, location_id: 280)
PalletLocation.create(pallet_id: 208, location_id: 281)
PalletLocation.create(pallet_id: 209, location_id: 282)
PalletLocation.create(pallet_id: 210, location_id: 284)
PalletLocation.create(pallet_id: 211, location_id: 285)
PalletLocation.create(pallet_id: 212, location_id: 286)
PalletLocation.create(pallet_id: 213, location_id: 287)
PalletLocation.create(pallet_id: 214, location_id: 290)
PalletLocation.create(pallet_id: 215, location_id: 291)
PalletLocation.create(pallet_id: 216, location_id: 292)
PalletLocation.create(pallet_id: 217, location_id: 293)
PalletLocation.create(pallet_id: 218, location_id: 296)
PalletLocation.create(pallet_id: 219, location_id: 297)
PalletLocation.create(pallet_id: 220, location_id: 298)
PalletLocation.create(pallet_id: 222, location_id: 302)
PalletLocation.create(pallet_id: 227, location_id: 309)
PalletLocation.create(pallet_id: 229, location_id: 311)
PalletLocation.create(pallet_id: 231, location_id: 315)
PalletLocation.create(pallet_id: 233, location_id: 317)
PalletLocation.create(pallet_id: 235, location_id: 321)
PalletLocation.create(pallet_id: 236, location_id: 322)
PalletLocation.create(pallet_id: 237, location_id: 323)
PalletLocation.create(pallet_id: 238, location_id: 326)
PalletLocation.create(pallet_id: 239, location_id: 327)
PalletLocation.create(pallet_id: 240, location_id: 328)
PalletLocation.create(pallet_id: 241, location_id: 329)
PalletLocation.create(pallet_id: 242, location_id: 338)
PalletLocation.create(pallet_id: 243, location_id: 339)
PalletLocation.create(pallet_id: 244, location_id: 340)
PalletLocation.create(pallet_id: 245, location_id: 341)
PalletLocation.create(pallet_id: 246, location_id: 344)
PalletLocation.create(pallet_id: 247, location_id: 345)
PalletLocation.create(pallet_id: 248, location_id: 346)
PalletLocation.create(pallet_id: 249, location_id: 347)
PalletLocation.create(pallet_id: 234, location_id: 320)
PalletLocation.create(pallet_id: 250, location_id: 350)
PalletLocation.create(pallet_id: 232, location_id: 316)
PalletLocation.create(pallet_id: 228, location_id: 310)
PalletLocation.create(pallet_id: 225, location_id: 305)
PalletLocation.create(pallet_id: 251, location_id: 351)
PalletLocation.create(pallet_id: 221, location_id: 299)
PalletLocation.create(pallet_id: 252, location_id: 352)
PalletLocation.create(pallet_id: 253, location_id: 353)
PalletLocation.create(pallet_id: 254, location_id: 356)
PalletLocation.create(pallet_id: 255, location_id: 357)
PalletLocation.create(pallet_id: 256, location_id: 308)
PalletLocation.create(pallet_id: 257, location_id: 303)
PalletLocation.create(pallet_id: 258, location_id: 314)
PalletLocation.create(pallet_id: 259, location_id: 358)
PalletLocation.create(pallet_id: 260, location_id: 359)
PalletLocation.create(pallet_id: 261, location_id: 362)
PalletLocation.create(pallet_id: 262, location_id: 363)
PalletLocation.create(pallet_id: 263, location_id: 364)
PalletLocation.create(pallet_id: 264, location_id: 365)
PalletLocation.create(pallet_id: 265, location_id: 368)
PalletLocation.create(pallet_id: 266, location_id: 369)
PalletLocation.create(pallet_id: 267, location_id: 370)
PalletLocation.create(pallet_id: 268, location_id: 371)
PalletLocation.create(pallet_id: 269, location_id: 374)
PalletLocation.create(pallet_id: 270, location_id: 375)
PalletLocation.create(pallet_id: 271, location_id: 376)
PalletLocation.create(pallet_id: 272, location_id: 377)
PalletLocation.create(pallet_id: 273, location_id: 380)
PalletLocation.create(pallet_id: 274, location_id: 381)
PalletLocation.create(pallet_id: 275, location_id: 382)
PalletLocation.create(pallet_id: 276, location_id: 383)
PalletLocation.create(pallet_id: 277, location_id: 386)
PalletLocation.create(pallet_id: 278, location_id: 387)
PalletLocation.create(pallet_id: 279, location_id: 388)
PalletLocation.create(pallet_id: 280, location_id: 389)
PalletLocation.create(pallet_id: 281, location_id: 392)
PalletLocation.create(pallet_id: 282, location_id: 393)
PalletLocation.create(pallet_id: 283, location_id: 394)
PalletLocation.create(pallet_id: 284, location_id: 395)
PalletLocation.create(pallet_id: 285, location_id: 404)
PalletLocation.create(pallet_id: 286, location_id: 405)
PalletLocation.create(pallet_id: 287, location_id: 406)
PalletLocation.create(pallet_id: 288, location_id: 407)
PalletLocation.create(pallet_id: 289, location_id: 410)
PalletLocation.create(pallet_id: 290, location_id: 411)
PalletLocation.create(pallet_id: 291, location_id: 412)
PalletLocation.create(pallet_id: 292, location_id: 413)
PalletLocation.create(pallet_id: 293, location_id: 416)
PalletLocation.create(pallet_id: 294, location_id: 417)
PalletLocation.create(pallet_id: 295, location_id: 418)
PalletLocation.create(pallet_id: 296, location_id: 419)
PalletLocation.create(pallet_id: 297, location_id: 422)
PalletLocation.create(pallet_id: 298, location_id: 423)
PalletLocation.create(pallet_id: 299, location_id: 424)
PalletLocation.create(pallet_id: 300, location_id: 425)
PalletLocation.create(pallet_id: 301, location_id: 428)
PalletLocation.create(pallet_id: 302, location_id: 429)
PalletLocation.create(pallet_id: 303, location_id: 430)
PalletLocation.create(pallet_id: 304, location_id: 431)
PalletLocation.create(pallet_id: 305, location_id: 434)
PalletLocation.create(pallet_id: 306, location_id: 435)
PalletLocation.create(pallet_id: 307, location_id: 436)
PalletLocation.create(pallet_id: 308, location_id: 437)
PalletLocation.create(pallet_id: 309, location_id: 440)
PalletLocation.create(pallet_id: 310, location_id: 441)
PalletLocation.create(pallet_id: 311, location_id: 442)
PalletLocation.create(pallet_id: 312, location_id: 443)
PalletLocation.create(pallet_id: 313, location_id: 446)
PalletLocation.create(pallet_id: 314, location_id: 447)
PalletLocation.create(pallet_id: 315, location_id: 448)
PalletLocation.create(pallet_id: 316, location_id: 449)
PalletLocation.create(pallet_id: 317, location_id: 452)
PalletLocation.create(pallet_id: 318, location_id: 453)
PalletLocation.create(pallet_id: 319, location_id: 454)
PalletLocation.create(pallet_id: 320, location_id: 455)
PalletLocation.create(pallet_id: 321, location_id: 458)
PalletLocation.create(pallet_id: 322, location_id: 459)
PalletLocation.create(pallet_id: 323, location_id: 460)
PalletLocation.create(pallet_id: 324, location_id: 461)
PalletLocation.create(pallet_id: 325, location_id: 470)
PalletLocation.create(pallet_id: 326, location_id: 471)
PalletLocation.create(pallet_id: 327, location_id: 472)
PalletLocation.create(pallet_id: 328, location_id: 473)
PalletLocation.create(pallet_id: 329, location_id: 476)
PalletLocation.create(pallet_id: 330, location_id: 477)
PalletLocation.create(pallet_id: 331, location_id: 478)
PalletLocation.create(pallet_id: 332, location_id: 479)
PalletLocation.create(pallet_id: 333, location_id: 482)
PalletLocation.create(pallet_id: 334, location_id: 483)
PalletLocation.create(pallet_id: 335, location_id: 484)
PalletLocation.create(pallet_id: 336, location_id: 485)
PalletLocation.create(pallet_id: 337, location_id: 488)
PalletLocation.create(pallet_id: 338, location_id: 489)
PalletLocation.create(pallet_id: 339, location_id: 490)
PalletLocation.create(pallet_id: 340, location_id: 491)
PalletLocation.create(pallet_id: 341, location_id: 494)
PalletLocation.create(pallet_id: 342, location_id: 495)
PalletLocation.create(pallet_id: 343, location_id: 496)
PalletLocation.create(pallet_id: 344, location_id: 497)
PalletLocation.create(pallet_id: 345, location_id: 500)
PalletLocation.create(pallet_id: 346, location_id: 501)
PalletLocation.create(pallet_id: 347, location_id: 502)
PalletLocation.create(pallet_id: 348, location_id: 503)
PalletLocation.create(pallet_id: 349, location_id: 506)
PalletLocation.create(pallet_id: 350, location_id: 507)
PalletLocation.create(pallet_id: 351, location_id: 508)
PalletLocation.create(pallet_id: 352, location_id: 509)
PalletLocation.create(pallet_id: 353, location_id: 512)
PalletLocation.create(pallet_id: 354, location_id: 513)
PalletLocation.create(pallet_id: 355, location_id: 514)
PalletLocation.create(pallet_id: 356, location_id: 515)
PalletLocation.create(pallet_id: 357, location_id: 518)
PalletLocation.create(pallet_id: 358, location_id: 519)
PalletLocation.create(pallet_id: 359, location_id: 520)
PalletLocation.create(pallet_id: 360, location_id: 521)
PalletLocation.create(pallet_id: 361, location_id: 530)
PalletLocation.create(pallet_id: 362, location_id: 531)
PalletLocation.create(pallet_id: 363, location_id: 532)
PalletLocation.create(pallet_id: 364, location_id: 533)
PalletLocation.create(pallet_id: 365, location_id: 596)
PalletLocation.create(pallet_id: 366, location_id: 597)
PalletLocation.create(pallet_id: 367, location_id: 598)
PalletLocation.create(pallet_id: 368, location_id: 599)
PalletLocation.create(pallet_id: 369, location_id: 662)
PalletLocation.create(pallet_id: 370, location_id: 663)
PalletLocation.create(pallet_id: 371, location_id: 664)
PalletLocation.create(pallet_id: 372, location_id: 665)
PalletLocation.create(pallet_id: 373, location_id: 728)
PalletLocation.create(pallet_id: 374, location_id: 729)
PalletLocation.create(pallet_id: 375, location_id: 730)
PalletLocation.create(pallet_id: 376, location_id: 731)
PalletLocation.create(pallet_id: 377, location_id: 794)
PalletLocation.create(pallet_id: 378, location_id: 795)
PalletLocation.create(pallet_id: 379, location_id: 796)
PalletLocation.create(pallet_id: 380, location_id: 797)
PalletLocation.create(pallet_id: 381, location_id: 860)
PalletLocation.create(pallet_id: 382, location_id: 861)
PalletLocation.create(pallet_id: 383, location_id: 862)
PalletLocation.create(pallet_id: 384, location_id: 863)
PalletLocation.create(pallet_id: 385, location_id: 925)
PalletLocation.create(pallet_id: 386, location_id: 926)
PalletLocation.create(pallet_id: 387, location_id: 927)
PalletLocation.create(pallet_id: 388, location_id: 928)
PalletLocation.create(pallet_id: 389, location_id: 982)
PalletLocation.create(pallet_id: 390, location_id: 983)
PalletLocation.create(pallet_id: 391, location_id: 984)
PalletLocation.create(pallet_id: 392, location_id: 985)
PalletLocation.create(pallet_id: 393, location_id: 1033)
PalletLocation.create(pallet_id: 394, location_id: 1034)
PalletLocation.create(pallet_id: 395, location_id: 1035)
PalletLocation.create(pallet_id: 396, location_id: 1036)
PalletLocation.create(pallet_id: 397, location_id: 536)
PalletLocation.create(pallet_id: 398, location_id: 537)
PalletLocation.create(pallet_id: 399, location_id: 538)
PalletLocation.create(pallet_id: 400, location_id: 539)
PalletLocation.create(pallet_id: 401, location_id: 542)
PalletLocation.create(pallet_id: 402, location_id: 543)
PalletLocation.create(pallet_id: 403, location_id: 544)
PalletLocation.create(pallet_id: 404, location_id: 545)
PalletLocation.create(pallet_id: 405, location_id: 548)
PalletLocation.create(pallet_id: 406, location_id: 549)
PalletLocation.create(pallet_id: 407, location_id: 550)
PalletLocation.create(pallet_id: 408, location_id: 551)
PalletLocation.create(pallet_id: 409, location_id: 554)
PalletLocation.create(pallet_id: 410, location_id: 555)
PalletLocation.create(pallet_id: 411, location_id: 556)
PalletLocation.create(pallet_id: 412, location_id: 557)
PalletLocation.create(pallet_id: 413, location_id: 560)
PalletLocation.create(pallet_id: 414, location_id: 561)
PalletLocation.create(pallet_id: 415, location_id: 562)
PalletLocation.create(pallet_id: 416, location_id: 563)
PalletLocation.create(pallet_id: 417, location_id: 566)
PalletLocation.create(pallet_id: 418, location_id: 567)
PalletLocation.create(pallet_id: 419, location_id: 568)
PalletLocation.create(pallet_id: 420, location_id: 569)
PalletLocation.create(pallet_id: 421, location_id: 572)
PalletLocation.create(pallet_id: 422, location_id: 573)
PalletLocation.create(pallet_id: 423, location_id: 574)
PalletLocation.create(pallet_id: 424, location_id: 575)
PalletLocation.create(pallet_id: 425, location_id: 578)
PalletLocation.create(pallet_id: 426, location_id: 579)
PalletLocation.create(pallet_id: 427, location_id: 580)
PalletLocation.create(pallet_id: 428, location_id: 581)


Location.find(2).update(available: false)
Location.find(3).update(available: false)
Location.find(4).update(available: false)
Location.find(5).update(available: false)
Location.find(68).update(available: false)
Location.find(69).update(available: false)
Location.find(70).update(available: false)
Location.find(71).update(available: false)
Location.find(134).update(available: false)
Location.find(135).update(available: false)
Location.find(136).update(available: false)
Location.find(137).update(available: false)
Location.find(138).update(available: false)
Location.find(200).update(available: false)
Location.find(201).update(available: false)
Location.find(203).update(available: false)
Location.find(202).update(available: false)
Location.find(266).update(available: false)
Location.find(267).update(available: false)
Location.find(268).update(available: false)
Location.find(269).update(available: false)
Location.find(270).update(available: false)
Location.find(332).update(available: false)
Location.find(333).update(available: false)
Location.find(334).update(available: false)
Location.find(335).update(available: false)
Location.find(398).update(available: false)
Location.find(399).update(available: false)
Location.find(401).update(available: false)
Location.find(464).update(available: false)
Location.find(466).update(available: false)
Location.find(465).update(available: false)
Location.find(525).update(available: false)
Location.find(527).update(available: false)
Location.find(8).update(available: false)
Location.find(9).update(available: false)
Location.find(11).update(available: false)
Location.find(400).update(available: false)
Location.find(526).update(available: false)
Location.find(10).update(available: false)
Location.find(14).update(available: false)
Location.find(15).update(available: false)
Location.find(16).update(available: false)
Location.find(17).update(available: false)
Location.find(467).update(available: false)
Location.find(524).update(available: false)
Location.find(18).update(available: false)
Location.find(20).update(available: false)
Location.find(21).update(available: false)
Location.find(23).update(available: false)
Location.find(22).update(available: false)
Location.find(26).update(available: false)
Location.find(29).update(available: false)
Location.find(30).update(available: false)
Location.find(32).update(available: false)
Location.find(34).update(available: false)
Location.find(33).update(available: false)
Location.find(35).update(available: false)
Location.find(38).update(available: false)
Location.find(39).update(available: false)
Location.find(40).update(available: false)
Location.find(41).update(available: false)
Location.find(42).update(available: false)
Location.find(44).update(available: false)
Location.find(45).update(available: false)
Location.find(46).update(available: false)
Location.find(47).update(available: false)
Location.find(50).update(available: false)
Location.find(51).update(available: false)
Location.find(52).update(available: false)
Location.find(53).update(available: false)
Location.find(56).update(available: false)
Location.find(57).update(available: false)
Location.find(58).update(available: false)
Location.find(59).update(available: false)
Location.find(62).update(available: false)
Location.find(63).update(available: false)
Location.find(64).update(available: false)
Location.find(65).update(available: false)
Location.find(74).update(available: false)
Location.find(75).update(available: false)
Location.find(76).update(available: false)
Location.find(77).update(available: false)
Location.find(80).update(available: false)
Location.find(81).update(available: false)
Location.find(82).update(available: false)
Location.find(83).update(available: false)
Location.find(86).update(available: false)
Location.find(87).update(available: false)
Location.find(88).update(available: false)
Location.find(89).update(available: false)
Location.find(92).update(available: false)
Location.find(93).update(available: false)
Location.find(94).update(available: false)
Location.find(95).update(available: false)
Location.find(98).update(available: false)
Location.find(99).update(available: false)
Location.find(100).update(available: false)
Location.find(101).update(available: false)
Location.find(104).update(available: false)
Location.find(105).update(available: false)
Location.find(107).update(available: false)
Location.find(110).update(available: false)
Location.find(111).update(available: false)
Location.find(112).update(available: false)
Location.find(116).update(available: false)
Location.find(117).update(available: false)
Location.find(118).update(available: false)
Location.find(119).update(available: false)
Location.find(122).update(available: false)
Location.find(123).update(available: false)
Location.find(124).update(available: false)
Location.find(125).update(available: false)
Location.find(128).update(available: false)
Location.find(129).update(available: false)
Location.find(130).update(available: false)
Location.find(131).update(available: false)
Location.find(140).update(available: false)
Location.find(141).update(available: false)
Location.find(142).update(available: false)
Location.find(143).update(available: false)
Location.find(146).update(available: false)
Location.find(147).update(available: false)
Location.find(113).update(available: false)
Location.find(148).update(available: false)
Location.find(149).update(available: false)
Location.find(28).update(available: false)
Location.find(27).update(available: false)
Location.find(152).update(available: false)
Location.find(153).update(available: false)
Location.find(154).update(available: false)
Location.find(155).update(available: false)
Location.find(158).update(available: false)
Location.find(161).update(available: false)
Location.find(165).update(available: false)
Location.find(166).update(available: false)
Location.find(167).update(available: false)
Location.find(170).update(available: false)
Location.find(171).update(available: false)
Location.find(172).update(available: false)
Location.find(173).update(available: false)
Location.find(176).update(available: false)
Location.find(177).update(available: false)
Location.find(178).update(available: false)
Location.find(179).update(available: false)
Location.find(182).update(available: false)
Location.find(183).update(available: false)
Location.find(184).update(available: false)
Location.find(185).update(available: false)
Location.find(188).update(available: false)
Location.find(189).update(available: false)
Location.find(190).update(available: false)
Location.find(191).update(available: false)
Location.find(194).update(available: false)
Location.find(195).update(available: false)
Location.find(196).update(available: false)
Location.find(160).update(available: false)
Location.find(106).update(available: false)
Location.find(159).update(available: false)
Location.find(164).update(available: false)
Location.find(197).update(available: false)
Location.find(206).update(available: false)
Location.find(207).update(available: false)
Location.find(208).update(available: false)
Location.find(209).update(available: false)
Location.find(212).update(available: false)
Location.find(213).update(available: false)
Location.find(214).update(available: false)
Location.find(215).update(available: false)
Location.find(218).update(available: false)
Location.find(219).update(available: false)
Location.find(220).update(available: false)
Location.find(221).update(available: false)
Location.find(224).update(available: false)
Location.find(225).update(available: false)
Location.find(226).update(available: false)
Location.find(227).update(available: false)
Location.find(230).update(available: false)
Location.find(231).update(available: false)
Location.find(232).update(available: false)
Location.find(233).update(available: false)
Location.find(236).update(available: false)
Location.find(237).update(available: false)
Location.find(238).update(available: false)
Location.find(242).update(available: false)
Location.find(243).update(available: false)
Location.find(239).update(available: false)
Location.find(245).update(available: false)
Location.find(248).update(available: false)
Location.find(250).update(available: false)
Location.find(254).update(available: false)
Location.find(255).update(available: false)
Location.find(256).update(available: false)
Location.find(257).update(available: false)
Location.find(260).update(available: false)
Location.find(261).update(available: false)
Location.find(262).update(available: false)
Location.find(263).update(available: false)
Location.find(249).update(available: false)
Location.find(272).update(available: false)
Location.find(273).update(available: false)
Location.find(274).update(available: false)
Location.find(275).update(available: false)
Location.find(279).update(available: false)
Location.find(280).update(available: false)
Location.find(281).update(available: false)
Location.find(282).update(available: false)
Location.find(284).update(available: false)
Location.find(285).update(available: false)
Location.find(286).update(available: false)
Location.find(287).update(available: false)
Location.find(290).update(available: false)
Location.find(291).update(available: false)
Location.find(292).update(available: false)
Location.find(293).update(available: false)
Location.find(296).update(available: false)
Location.find(297).update(available: false)
Location.find(298).update(available: false)
Location.find(302).update(available: false)
Location.find(309).update(available: false)
Location.find(311).update(available: false)
Location.find(315).update(available: false)
Location.find(317).update(available: false)
Location.find(321).update(available: false)
Location.find(322).update(available: false)
Location.find(323).update(available: false)
Location.find(326).update(available: false)
Location.find(327).update(available: false)
Location.find(328).update(available: false)
Location.find(329).update(available: false)
Location.find(338).update(available: false)
Location.find(339).update(available: false)
Location.find(340).update(available: false)
Location.find(341).update(available: false)
Location.find(344).update(available: false)
Location.find(345).update(available: false)
Location.find(346).update(available: false)
Location.find(347).update(available: false)
Location.find(320).update(available: false)
Location.find(350).update(available: false)
Location.find(316).update(available: false)
Location.find(310).update(available: false)
Location.find(305).update(available: false)
Location.find(351).update(available: false)
Location.find(299).update(available: false)
Location.find(352).update(available: false)
Location.find(353).update(available: false)
Location.find(356).update(available: false)
Location.find(357).update(available: false)
Location.find(308).update(available: false)
Location.find(303).update(available: false)
Location.find(314).update(available: false)
Location.find(358).update(available: false)
Location.find(359).update(available: false)
Location.find(362).update(available: false)
Location.find(363).update(available: false)
Location.find(364).update(available: false)
Location.find(365).update(available: false)
Location.find(368).update(available: false)
Location.find(369).update(available: false)
Location.find(370).update(available: false)
Location.find(371).update(available: false)
Location.find(374).update(available: false)
Location.find(375).update(available: false)
Location.find(376).update(available: false)
Location.find(377).update(available: false)
Location.find(380).update(available: false)
Location.find(381).update(available: false)
Location.find(382).update(available: false)
Location.find(383).update(available: false)
Location.find(386).update(available: false)
Location.find(387).update(available: false)
Location.find(388).update(available: false)
Location.find(389).update(available: false)
Location.find(392).update(available: false)
Location.find(393).update(available: false)
Location.find(394).update(available: false)
Location.find(395).update(available: false)
Location.find(404).update(available: false)
Location.find(405).update(available: false)
Location.find(406).update(available: false)
Location.find(407).update(available: false)
Location.find(410).update(available: false)
Location.find(411).update(available: false)
Location.find(412).update(available: false)
Location.find(413).update(available: false)
Location.find(416).update(available: false)
Location.find(417).update(available: false)
Location.find(418).update(available: false)
Location.find(419).update(available: false)
Location.find(422).update(available: false)
Location.find(423).update(available: false)
Location.find(424).update(available: false)
Location.find(425).update(available: false)
Location.find(428).update(available: false)
Location.find(429).update(available: false)
Location.find(430).update(available: false)
Location.find(431).update(available: false)
Location.find(434).update(available: false)
Location.find(435).update(available: false)
Location.find(436).update(available: false)
Location.find(437).update(available: false)
Location.find(440).update(available: false)
Location.find(441).update(available: false)
Location.find(442).update(available: false)
Location.find(443).update(available: false)
Location.find(446).update(available: false)
Location.find(447).update(available: false)
Location.find(448).update(available: false)
Location.find(449).update(available: false)
Location.find(452).update(available: false)
Location.find(453).update(available: false)
Location.find(454).update(available: false)
Location.find(455).update(available: false)
Location.find(458).update(available: false)
Location.find(459).update(available: false)
Location.find(460).update(available: false)
Location.find(461).update(available: false)
Location.find(470).update(available: false)
Location.find(471).update(available: false)
Location.find(472).update(available: false)
Location.find(473).update(available: false)
Location.find(476).update(available: false)
Location.find(477).update(available: false)
Location.find(478).update(available: false)
Location.find(479).update(available: false)
Location.find(482).update(available: false)
Location.find(483).update(available: false)
Location.find(484).update(available: false)
Location.find(485).update(available: false)
Location.find(488).update(available: false)
Location.find(489).update(available: false)
Location.find(490).update(available: false)
Location.find(491).update(available: false)
Location.find(494).update(available: false)
Location.find(495).update(available: false)
Location.find(496).update(available: false)
Location.find(497).update(available: false)
Location.find(500).update(available: false)
Location.find(501).update(available: false)
Location.find(502).update(available: false)
Location.find(503).update(available: false)
Location.find(506).update(available: false)
Location.find(507).update(available: false)
Location.find(508).update(available: false)
Location.find(509).update(available: false)
Location.find(512).update(available: false)
Location.find(513).update(available: false)
Location.find(514).update(available: false)
Location.find(515).update(available: false)
Location.find(518).update(available: false)
Location.find(519).update(available: false)
Location.find(520).update(available: false)
Location.find(521).update(available: false)
Location.find(530).update(available: false)
Location.find(531).update(available: false)
Location.find(532).update(available: false)
Location.find(533).update(available: false)
Location.find(596).update(available: false)
Location.find(597).update(available: false)
Location.find(598).update(available: false)
Location.find(599).update(available: false)
Location.find(662).update(available: false)
Location.find(663).update(available: false)
Location.find(664).update(available: false)
Location.find(665).update(available: false)
Location.find(728).update(available: false)
Location.find(729).update(available: false)
Location.find(730).update(available: false)
Location.find(731).update(available: false)
Location.find(794).update(available: false)
Location.find(795).update(available: false)
Location.find(796).update(available: false)
Location.find(797).update(available: false)
Location.find(860).update(available: false)
Location.find(861).update(available: false)
Location.find(862).update(available: false)
Location.find(863).update(available: false)
Location.find(925).update(available: false)
Location.find(926).update(available: false)
Location.find(927).update(available: false)
Location.find(928).update(available: false)
Location.find(982).update(available: false)
Location.find(983).update(available: false)
Location.find(984).update(available: false)
Location.find(985).update(available: false)
Location.find(1033).update(available: false)
Location.find(1034).update(available: false)
Location.find(1035).update(available: false)
Location.find(1036).update(available: false)
Location.find(536).update(available: false)
Location.find(537).update(available: false)
Location.find(538).update(available: false)
Location.find(539).update(available: false)
Location.find(542).update(available: false)
Location.find(543).update(available: false)
Location.find(544).update(available: false)
Location.find(545).update(available: false)
Location.find(548).update(available: false)
Location.find(549).update(available: false)
Location.find(550).update(available: false)
Location.find(551).update(available: false)
Location.find(554).update(available: false)
Location.find(555).update(available: false)
Location.find(556).update(available: false)
Location.find(557).update(available: false)
Location.find(560).update(available: false)
Location.find(561).update(available: false)
Location.find(562).update(available: false)
Location.find(563).update(available: false)
Location.find(566).update(available: false)
Location.find(567).update(available: false)
Location.find(568).update(available: false)
Location.find(569).update(available: false)
Location.find(572).update(available: false)
Location.find(573).update(available: false)
Location.find(574).update(available: false)
Location.find(575).update(available: false)
Location.find(578).update(available: false)
Location.find(579).update(available: false)
Location.find(580).update(available: false)
Location.find(581).update(available: false)
